app:
  # ✏️ CUSTOMIZE: Set to your deployment URL
  baseUrl: ${APP_BASE_URL}

backend:
  # ✏️ CUSTOMIZE: Set to your backend deployment URL
  baseUrl: ${BACKEND_BASE_URL}
  listen: ':7007'

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  providers:
    github:
      production:
        # ✏️ CUSTOMIZE: Create a GitHub OAuth App for production
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, Group, User, Resource, Location, Template, API]

  locations:
    - type: file
      target: ./catalog-entities/all.yaml

  # ✏️ CUSTOMIZE: Change 'POps-Rox' to your GitHub org name
  providers:
    github:
      popsRoxOrg:
        organization: 'POps-Rox'
        catalogPath: '/catalog-info.yaml'
        filters:
          repository: '.*'
        schedule:
          frequency: { minutes: 30 }
          timeout: { minutes: 3 }

  useUrlReadersSearch: true
